### ISSUE TITLE
Lab 4: Fail test case 9_03

### ISSUE THREAD

**Issue by vvivianfang** [nus-cs2030/2324-s1#103]
<img width="363" alt="image" src="https://github.com/nus-cs2030/2324-s1/assets/133471507/0ef95310-86ca-428d-9041-ab2c14843aee">
my code passes the cases in cc but not the private test case, how can i approach this error

**Comment by wjunwei2001** [comment]
TLE errors in cs2030 almost always come from an infinite loop problem since efficiency is not the focus. Hence if you are encountering this error, it means that somewhere in your program there is an infinite loop occurring. One such possibility is perhaps how you handle the wait event, if the customer is continuously kept in the wait event then the program won't end. That said there are many possibilities. If you can provide more information with your testing that would be helpful since we can't really tell anything from this alone
