### ISSUE TITLE
Guidance regarding Ungraded Exercise (Random)

### ISSUE THREAD

**Issue by YHWong20** [nus-cs2030/2324-s1#132]
Hello, I was wondering if anyone here is willing to give some tips for this exercise? 

I'm not sure if my current approach is correct - I'm thinking of using a Supplier to return the mapped/unmapped value lazily, so I'm making Rand a generic class, but in doing so I'm having trouble trying to modify the next() and map() methods, to make use of the generic Supplier.

Would really appreciate any advice or help for this. Thank you!!

**Comment by saddle196883** [comment]
I went about having two attributes in my Rand<T> class, an int value and a Function<Integer, T>.

**Comment by Yihan2407** [comment]
Like @saddle196883 mentioned, you can consider storing only the seed and a Function<Integer, T> in the generic class Rand. That way, you can do lazy evaluation by applying the Function only when you call .get(), so I don't think there is a need for a supplier to my knowledge though you can probably use one if you like.

**Comment by YHWong20** [comment]
Thanks all. Yeah, Function is indeed the correct way to do it.

I spent the last 1-2 hours thinking of a way to use Supplier but I don't think it is possible.

**Comment by vvivianfang** [comment]
hello we cannot use map in randRange right? cos i submitted and they say multiple references made

**Comment by kirin46** [comment]
hi, may i know what is the purpose of Function<Integer, T>? thank you!

**Comment by saddle196883** [comment]
If the order of ``map`` and ``next`` doesn't matter, then we can delay applying the map as late as possible. Thus you can carry around a function ``Integer -> T`` that stores the map you will eventually need to apply. Interesting things happen after you do that.

- The ``map``/``flatMap`` then works by just composing onto this function.
- ``Rand.of`` provides a unified starting point for the client to use the Rand class, and the function ``Integer-> Integer`` is just the identity.
- Your answer will be definitely right because if evaluation is made as late as possible all the time, and of course the order of applying ``map`` and ``next`` will not matter.
