### ISSUE TITLE
Functor vs. Monad

### ISSUE THREAD

**Issue by dianeteo** [nus-cs2030/2324-s1#137]
What is the difference between a functor and a monad? And does this have anything to do with right/left identity?

**Comment by SooYap** [comment]
A functor is basically a class or object that has the map method. It is able to transform whatever object that is enclosed within your functor into another type through a handy function.
Functor has to obey certain laws.

Identity law of Functors:
If you call map with an identity function on a Functor, you get the same Functor back.

Associativity law of Functors:
If you call the map with the function f, and then map with the function g on the Functor, it is equivalent to calling map with the function f.andThen(g), or g.compose(f) on the Functor.

Monad on the other hand is something with flatMap. You have a function which returns a Functor instead of whatever was wrapped inside the Functor, and so now you have to flatten it. 

Similarly, Monad obeys certain laws too.

Here is where things get tricky. A Monad has to obey the left and right identity laws. 
Left identity law:
Suppose you have a Monad (named monad). You have the following method call:
monad.flatMap.(x -> Monad.of(x)) 
This is equivalent to calling monad.

Right identity law:
Suppose you have a function f(x) which returns a monad. Then you have the following method call:
Monad.of(x).flatMap(x -> f(x))
This is equivalent to calling f(x).

And lastly, we have the associativity law for Monads:
Suppose you want to compose two functions using flatMap. You would write something like:
monad.flatMap(x -> f(x)).flatMap(y -> g(x))
An equivalent way of writing this is monad.flatMap(x -> f(x).flatMap(y -> g(y)))

Hope this helps!
