### ISSUE TITLE
Question about the Main used to test OO implementation

### ISSUE THREAD

**Issue by viniciusat3** [nus-cs2030/2324-s1#16]
I don't understand the proposed structure for Main.

Why would Inputs create ImLists instead of objects? And, more importantly, why would the Simulator class use (numOfServers, arrivalTimes, serviceTimes) as parameters instead of the new classes we are creating? (e.g. a list of Customer objects and Server objects)

Thank you

**Comment by somethingfishyfishy** [comment]
I dont really understand what you mean by
> Why would Inputs create ImLists instead of objects?

Anyways, the input files ("1.in") does not create an ImList, the main() function in Main.java file does. Eitherways, the reason why the arguments are passed as it is to the simulator class is to keep Main.java in tact, so that the classes created are basically the files that you have to write. 
Eg. "ImList<Double>, ImList<Double>" are passed instead of "ImList<Customer>, ImList<Server>" so that you create the ImList<Customer>, ImList<Server> in your simulator class instead.

Why would you want to maintain the Main.java as in tact as it is? Cause its cleaner and more readable, and probably mainly because the Main file is not meant to be edited so the tester can test properly.
