### ISSUE TITLE
Lab 3: Space between output lines

### ISSUE THREAD

**Issue by vvivianfang** [nus-cs2030/2324-s1#23]
<img width="396" alt="Screenshot 2023-09-20 at 2 00 11 AM" src="https://github.com/nus-cs2030/2324-s1/assets/133471507/0ea22f72-03d3-4922-9a8d-6f09e3c914ae">

<img width="361" alt="image" src="https://github.com/nus-cs2030/2324-s1/assets/133471507/57a9deb9-ace7-4f99-8c98-d0be1d56be6f">

How do I remove the line between my outputs?

**Comment by somethingfishyfishy** [comment]
You probably had an extra "\n" somewhere

**Comment by PVT-LF** [comment]
I am assuming you are using the `toString()` method of each event to get an output which will be concatenated as the output of `simulate()`. I also assume that in your implementations of the `toString()` method a newline is not added to the end of the returned string e.g. in the format `"X.XXX Y waits at Z"` instead of `"X.XXX Y waits at Z\n"`.

If this is the case, an alternative possibility, which is more difficult to detect, is that there may be some dummy event which is somehow added to your event PQ which still returns an empty string when its `toString()` method is called.

This may imply that some additional events are somehow added to your PQ as an unintended effect due to a bug / programming error. You may want to check if any undesired events have been added to your PQ of events; this may be causing the problem.

**Comment by vvivianfang** [comment]
I found the error thanks to your help! Thank you @PVT-LF @somethingfishyfishy !
