### ISSUE TITLE
Unable to access CodeCrunch

### ISSUE THREAD

**Issue by roderickvo** [nus-cs2030/2324-s1#30]
Hello Prof, currently I am unable to open codecrunch to open the exercise and submit my answers. Is there an issue with codecrunch right now or is it only on my laptop? Thank you!

**Comment by hwkchia** [comment]
Reproducing the announcement from Canvas here:

Unavailability of CodeCrunch on 30 Sep
[Chia Wai Kit, Henry](https://canvas.nus.edu.sg/courses/45642/users/51185)

Dear all,

I was not informed of the unavailability of CodeCrunch during the Disaster Recovery Drill period.

As such, when I get the chance to access CodeCrunch again, I shall extend all deadlines to 5 October 23:59pm.  I understand that some students are intending to spend these two days to finish up on all the CS2030 deliverables, but due to this hiccup they are not able to progress as planned.  Since the coming week is the week of midterms, I also do not wish that students sacrifice their preparation for other courses just for the sake of completing our deliverables.  Hence I have extended the deadline till the coming Thursday in the hopes that this will alleviate some of your concerns.

**Comment by roderickvo** [comment]
Alright thank you so much prof!
