### ISSUE TITLE
Mock PA Autograder: Calls a "PrivateCarX" constructor? (Test case 6)

### ISSUE THREAD

**Issue by PVT-LF** [nus-cs2030/2324-s1#33]
# Summary
I don't know what's up but for some reason a PrivateCar**X** (`PrivateCarX`) constructor is called. I'll let the screenshot do the rest.

## Screenshots

![Screenshot (325)](https://github.com/nus-cs2030/2324-s1/assets/63499294/4e32fb9f-325a-460a-a66e-f271fd0e1bb8)

**Comment by nearsea00** [comment]
I think some of the test cases in CodeCrunch include new classes to test if your code is modular and can be easily extended. In this case, I think it's testing if your Booking class is taking in a general Driver class instead of specifically PrivateCar or NormalCab in its constructor. I'm assuming PrivateCarX is extending/implementing an abstract class/interface Driver. If that's true, it could also be an issue with your class names. I used an abstract class Driver and I was able to pass this test case.

I could also be entirely wrong and the DR drill earlier messed with the autograder. I submitted my files before that and I didn't encounter the same issue.

**Comment by PVT-LF** [comment]
If the symbol was not found it means the class was not even opened in JShell, i.e. attempting to create a new PrivateCarX object when the class definition does not even exist.

Otherwise the error would occur from the Booking constructor, that no such constructor allowing for a PrivateCarX to be passed in exists, for example.

**Comment by hwkchia** [comment]
fyi, `PrivateCarX` will also be dropped by jshell if it cannot be compiled against the functionality of some existing classes. In other words, for `PrivateCarX` to be accepted, "some existing classes" need to be modified.  That's how we test whether the design of the classes are appropriate.
