### ISSUE TITLE
Exercise 2

### ISSUE THREAD

**Issue by e0970359** [nus-cs2030/2324-s1#34]
Why is there a string of numbers behind?
<img width="394" alt="Screenshot 2023-10-05 at 3 38 20 PM" src="https://github.com/nus-cs2030/2324-s1/assets/145977561/57463cfa-d112-41b7-8c16-8098de80cfff">

**Comment by jueyaolim** [comment]
It's the memory address/hashcode of which the object is stored. In this case the default public String toString() method is called onto (from the Object class, the mother of everything haha) which is why it shows the string of numbers behind. You'll need to override it with @Override and your own declaration of the new toString() method.

**Comment by jueyaolim** [comment]
https://www.geeksforgeeks.org/object-tostring-method-in-java/
