### ISSUE TITLE
Lab 4 Fail Test Case: 9_03

### ISSUE THREAD

**Issue by limefreak** [nus-cs2030/2324-s1#38]
# Summary

Ran into testcase fail, has anyone passed this?

## Description:

Looks like customer 3 is strange here.
It goes into server 2 instead of server 1 even though server 1 is done serving.
Perhaps server 1 isn't told to rest? I think I implemented this well though.
Any other ideas why I'm failing the testcase?

## Code Snippets

I can't T-T

## Screenshots

![image](https://github.com/nus-cs2030/2324-s1/assets/97215727/b180e3bf-a67f-40d6-be48-8bfea35ff3ca)

**Comment by ChoonHean** [comment]
Yes i passed it. By the looks of the expected output, 1 is supposed to be resting when 3 arrives

**Comment by somethingfishyfishy** [comment]
> Perhaps server 1 isn't told to rest? I think I implemented this well though.

Precisely because server1 is told to rest, so when cust3 arrives, cust3 is served by server2
My suggestion is to check where you implemented the action of giving rest to server.
---> think whether if this place is the right place to implement the action of giving rest
---> For example, is a Wait/Arrive/Serve event happening before you performed the action of giving rest

**Comment by limefreak** [comment]
Derp, I was trying to fix all the rest methods but I realized after some trying that this is the output returned when none of the servers rest. Therefore, my server isn't resting. All it took was a server = server.rest() in Simulator....
