### ISSUE TITLE
Maybe.of() concern in Exercise 04

### ISSUE THREAD

**Issue by JerryWang0000** [nus-cs2030/2324-s1#42]
We can do
 `Maybe<Object> mo = Maybe.of(123);`
However, I thought generics are invariant. And the output of `Maybe.of(123);` is of type Maybe<Integer> and it is invariant to Maybe<Object>. However the expression is legit. I don't understand as there is no wildcard involved in the definition.
![image](https://github.com/nus-cs2030/2324-s1/assets/148452043/f41e9916-30c7-4369-a8e4-d7ff0b2ab0b2)

**Comment by yiiilonggg** [comment]
hi! i tried this out on jshell. when i did Maybe.of(123) alone and checked its type, it is of Maybe<Integer>. we can also type witness the assignment of "Maybe<Object> mo = Maybe.of(123)" to
```
Maybe<Object> mo = Maybe.<Object>of(123); // this is ok
Maybe<Object> mo = Maybe.<Integer>of(123); // this is not ok
```
which makes sense since generics are invariant. it seems as though java first tries to bind Integer to T (since when doing Maybe.of(123) alone results in a Maybe<Integer>), then realises it cannot assign a Maybe<Integer> to Maybe<Object>, so it tries the classes that Integer extends from until it reaches Object. So Object binds to T, and Maybe.<Object>of(123) is legal since an Integer is-a(n) Object, and Maybe<Object> is-a Maybe<Object> so the assignment is legal too.

ps feel free to correct me if im wrong

**Comment by JerryWang0000** [comment]
I asked ChatGPT and it said that the mechanism is called Type Inference. So it is not a Maybe parameterized by Integer, but a Maybe that is carrying an Integer. It is like how we initialize an ArrayList without specifying the type. If we write `Maybe<Object> mo = Maybe.<Integer>of(123);` it is equivalent to parameterizing a Maybe Instance with Integer.

**Comment by hwkchia** [comment]
`Maybe<Object> mo = Maybe.<Integer>of(123); // this is not ok`
This is violating invariance of generics.
That's why we need to go through bounded wildcards:
`Maybe<? extends Object> mo = Maybe.<Integer>of(123); // works!`
