### ISSUE TITLE
Issue with compiling Course class

### ISSUE THREAD

**Issue by WinstonJin** [nus-cs2030/2324-s1#49]
Anyone have any idea why my Course.java is not compiling properly? The Assessment class implements Keyable so I don't see why this shows an error
<img width="454" alt="Screenshot 2023-10-21 at 17 57 21" src="https://github.com/nus-cs2030/2324-s1/assets/142196043/a0f07a50-85db-4913-9fd7-644336e36c35">
<img width="612" alt="Screenshot 2023-10-21 at 17 57 16" src="https://github.com/nus-cs2030/2324-s1/assets/142196043/b1aac372-24f1-4839-93bd-695278519ef2">
<img width="721" alt="Screenshot 2023-10-21 at 17 57 06" src="https://github.com/nus-cs2030/2324-s1/assets/142196043/caf6b76e-af61-4e12-9735-9e546be3b21e">

**Comment by ChoonHean** [comment]
Your course extends KeyableMap<Assessment>, which means that you need to construct a KeyableMap(String key, ImmutableMap<String, V> value) using super(key, value), which you did not

**Comment by AbdulrahmanAlRammah** [comment]
When creating the constructor for a subclass you need to use the constructor of the superclass. You also need not redefine attributes.

For example, my super class has constructor (int x, int y)

my subclass has 
private final int z;

constructor (int x, int y, int z) {
super(x, y);
this.z = z;

You define the new variable that belongs to the subclass and not the superclass and you use the supers constructor to take in arguments pertaining to it.

The error says it didn't find anything because u defined 2 new variables. Your class course has 4 attributes 2 from the super and 2 new ones you defined. The 2 you defined have been initialized but the two from super were not. Thus, you have to do something like above.

**Comment by jodooi** [comment]
You can try deleting the 2 private final attributes, and replace the this.__ = __ with super(key, map), refer to lec 4 for more info
