### ISSUE TITLE
Probability of Server taking a rest

### ISSUE THREAD

**Issue by vicelyav** [nus-cs2030/2324-s1#50]
# Summary

Description of the question / problem here.

## Description: Hi everyone, I'm a bit confused on how to know when the human server takes breaks. I know that the supplier will determine the duration of the break, but I'm not sure how to determine when the human server specifically takes the break. Is it we use the same supplier provided in the main class? Any clarification will be appreciated, thank you

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

## Screenshots

Screenshots (if any)

**Comment by tata32000** [comment]
I think you can add the break duration to the server class and call it once the human server done serving the customer. To use the supplier, we can use it like in the customer service time from the previous lab. 

We ask for a rest time from supplier only when the server is done serving the customer just like you ask service time from supplier when you serve a customer.

**Comment by ChoonHean** [comment]
It is true that the rest time is 0 when the server does not take a break. If you look at Main.java, 
`Supplier<Double> restTimes = () -> RNG_REST.nextDouble() < probRest ? genRestPeriod() : 0.0;`
RNG_REST.nextDouble() is a random double between 0 and 1, if it is less than the probability of rest, then genRestPeriod() is called, otherwise the rest period is 0.0.

**Comment by YHWong20** [comment]
You have a Supplier that generates rest times. Calling .get() on the rest time Supplier returns a randomly generated rest time for the human server, so call it only when you need to (i.e. during/after your done event, depending on your design).

Just like the customer's service time Supplier, it should be taken in and used by your Simulator in Main.java. From there on, you will need to make use of the rest time Supplier. Again, how you use the Supplier depends on your design.

**Comment by somethingfishyfishy** [comment]
The question of when you should call .getRestTime() is answered in the earlier comments. Ask if you require more clarifications.

On another note, if I interpret your question correctly.. "Is it we use the same supplier provided in the main class?", if you are asking if each server get a distinct Supplier of restTimes or the servers all share from the same pool of restTimes -- it is the second scenario. Each server will get RestTime from the same Supplier.

**Comment by R0yden** [comment]
Everytime a human server serves a customer, you get a rest time from the rest time Supplier. Within the supplier, it already handles the generating of probabilities and the supplier will return a rest time of 0 or the stated rest time depending on what probability was generated. You should treat this as all being abstracted away within the Supplier so that you only have to bother about getting a rest time from the Supplier.

**Comment by vvhuiling** [comment]
Yes we are using the same supplier for all RestEvent. when you generate it, you simply get the next random value from the supplier, so the timing of generate breaktime will be critical, or mismatch between different server may happen.
