### ISSUE TITLE
Ex 3: test case 4 (level 3/5 serveCruises method)

### ISSUE THREAD

**Issue by kirin46** [nus-cs2030/2324-s1#52]
may i know if anyone else got this same error? im not sure where my logic for the serveCruises method is wrong as the test cases provided works fine. i did:
for every cruise: 
- loop through active and if any services end time has passed, remove and add to expired
- loop through expired and create new service for cruise
- if not enough loaders yet, create more and if the loader's id % 3 == 0, create a RecycledLoader instead.
Thanks for the help in advance!

<img width="842" alt="Screenshot 2023-10-22 at 12 32 35 PM" src="https://github.com/nus-cs2030/2324-s1/assets/120187114/5942f8fe-eaaf-462b-8a97-7b9245aa2419">

**Comment by jodooi** [comment]
I had this same issue, not sure if its the same problem. You can try check your BigCruise.getServiceTime(), did you account for the remainder timing after division? ie. if passengers = 140, when divided by 50 , should be 3 instead of 2 to account for the excess. same as the getNumOfLoadersRequired() method.

**Comment by kirin46** [comment]
ohh i see, seems like that was the problem. thank you for your help!
