### ISSUE TITLE
lab5 wrong output in Course class 

### ISSUE THREAD

**Issue by jjiehh** [nus-cs2030/2324-s1#55]
# Summary
i wasn't able to get the correct output as required in the jshell 

## Description:

the required output is CS2040: {Lab1: B, Lab2: A+} while i got CS2040: {Lab1=B, Lab2=A+}

## Code Snippets

Attach code snippets (if any)

## Screenshots
<img width="751" alt="Screenshot 2023-10-23 at 8 45 36 AM" src="https://github.com/nus-cs2030/2324-s1/assets/142228944/8cfdf207-157f-487a-8f36-d0ca91e9b0a7">

**Comment by YHWong20** [comment]
I believe `{Lab1=B, Lab2=A+}` is the default String representation of a HashMap. Consider overriding your toString() method in your class so you can achieve the desired output String.

**Comment by jjiehh** [comment]
but both Assessment class and Course class i have included @Override for both toString() method

**Comment by YHWong20** [comment]
Hmm, assuming that your Assessment's toString() method is correct, then I would probably guess that the toString() method in your Course isn't using the Assessment's toString() method. Are you perhaps accessing the ImmutableMap directly?

i.e., Are you printing the ImmutableMap instead of an Assessment?

**Comment by jjiehh** [comment]
in the put method, it takes in the Assessment as the parameter and return a new Course with the course name and an ImmutableMap of the assessment's key and its grade. not sure if im doing it right

**Comment by YHWong20** [comment]
So looking at your description, I'm guessing your Course has an `ImmutableMap<String, String>` to store assessments? Do correct me if I'm wrong. 

If that is the case, then you have to account for that in your Course's toString() method - that is, you need to iterate over your ImmutableMap and retrieve each corresponding assessment key and grade, to format into your eventual returned String (i.e. the output of toString()). Simply taking the String representation of the ImmutableMap will not be correct.

FWIW, I think your implementation is doable, but it might become quite tricky to do up the toString() method. Not sure if your TA has advised you to do so, but read ahead and take a look at Level 3 first, because there is a strong chance you will need to re-do your Course implementation. Take a look at KeyableMap and see what similarities it has to your Course class.  

<details>
<summary> Hint </summary>
Consider using an ImmutableMap<String, Assessment> within your Course instead. If you do this, you can make use of the overridden toString() for your Assessment class. Then, doing the toString() method becomes much simpler.
</details>
