### ISSUE TITLE
Lab 4: Fail Test Case 9_03

### ISSUE THREAD

**Issue by nearsea00** [nus-cs2030/2324-s1#62]
# Summary

The issue seems to come from differences between the server rest times in the expected and actual output. 

## Description:

I was able to pass the test cases provided in the lab instructions so I'm not sure why there's a problem with this specific test case.
I'm updating my server rest in my Done event and that's the only place I'm calling restTimes.get().

## Screenshots
![image](https://github.com/nus-cs2030/2324-s1/assets/145828376/9f851b31-6bf7-4d59-9e8d-e95a0644c612)

**Comment by yiiilonggg** [comment]
hello! when the event "15.013 11 serves by 1" occurs, what is the state of server 1? has it been updated by the rest time?

also, if you want to only test the behaviour of rest, i can suggest getting a list of the supplier's rest times first. one of the test cases provides a supplier with the same behaviour (some 0 rest times in between non-zero rest times). from the list, you can create a test case of 1 human server with some queue size. then slowly trace the DES simulation as you insert the customers and their arrival times to simulate different cases your human server can face.

sometimes i felt it was quite hard to debug directly from the output of code crunch because of the 0 rest times, so the error could have occurred somewhere above in my code.

hope this helps!

**Comment by somethingfishyfishy** [comment]
You should be updating the Server's availableTime in Done, that logic is correct. This is what I suspect might be happening.

Ignoring cust13 for the outputs below

**Expected:**
7.xxx 10 waits at 1 _[update to Serve(14.644, cust10, serv1)]_
8.yyy 11 waits at 1 _[update to Wait(14.644, cust11, serv1)]_
14.644 10 serves by 1 _[update AvailTime(serv1, 15.013), update to Done(15.013, cust10, serv1)]_
_14.644 11 was waiting at 1 [update to **Wait**(**15.013**, cust11, serv1)]_
15.013 10 done serving by 1 _[update AvailTime(serv1, 40.474)]_
_15.013 11 was waiting at 1 [update to Serve(40.474, cust11, serv1)]_
40.474 11 serves by 1 _[update AvailTime(...)]_

**Your code could be running:**
7.xxx 10 waits at 1 _[update to Serve(14.644, cust10, serv1)]_
8.yyy 11 waits at 1 _[update to Wait(14.644, cust11, serv1)]_
14.644 10 serves by 1 _[update AvailTime(serv1, 15.013), update to Done(15.013, cust10, serv1)]_
_14.644 11 was waiting at 1 [update to **Serve**(**15.013**, cust11, serv1)]_
15.013 10 done serving by 1 _[update AvailTime(serv1, 40.474)]_
15.013 11 serves by 1 _[update AvailTime(serv1, zzz) to Done(...)]_

_Italicised means not printed_

This is one possible reason I can think of why your output is failing. You might have allowed the possibility for assigning to Serve from "Waiting" to occur before your Done event. 

@yiiilonggg mentioned
> when the event "15.013 11 serves by 1" occurs, what is the state of server 1? has it been updated by the rest time?

I believe the serv1 has the correct AvailTime, since the author says that he/she passed the public cases. The problem is likely arising from updating Wait Events

**Comment by Yihan2407** [comment]
Hi, not sure if this is solved already but I believe the public test case provided in the lab does not account for the situation whereby there is more than one customer waiting in the queue which simplifies the problem a lot.

If your logic was previously:
a.) Customer waits at server (generates ServeWaitingCustomer event if customer is first in queue else continue waiting ) 
b.) Waiting customer is served (generates ServiceDone event)

Consider the case whereby the server takes a rest, which is only generated at the Done event -- this will result in the ServeWaitingCustomer event occurring at the wrong time as it uses the availability time of the server before he is done (i.e., before accounting for the rest time)

To tackle this, you can consider allowing each Wait event to generate an additional Wait event that accounts for the server resting, then generating a Serve event based on a moving index within the Wait event. For example, if there is only one customer in the queue, a Wait event is generated at the time the customer joins the queue. Next, this Wait event can generate another Wait event that occurs at the server's available time (when they finish serving but before resting) to check if the server rests, then generate a Serve event from there which will take care of the case whereby the Server either rests or does not rest.

Next, you can extend this to the case whereby there is more than 1 customer in the queue. Imagine if there are 2 customers waiting:
a.) Cust 3 has to wait in the queue (2nd in queue) 
b.) Cust 3 waits for Customer 1 to be done serving
c.) Cust 3 waits again to see if Server has to rest
d.) Cust 2 (1st in queue) is served -- Cust 3 continues waiting for Cust 2 to be done serving (becomes 1st in queue)
e.) Cust 3 now waits again to see if Server has to rest
f.) Cust 3 is served

At each wait event, you should also check for the server's availability time, which will be updated based on the service time and the possibility of the server resting, then implement your ServeWaitingCustomer event and Wait event correspondingly.

**Comment by JerryWang0000** [comment]
My way of debugging is to write my own input where there are excessively many customers and limited servers(Should try 1 and 2 servers of only 1 type). Such case is not involved in the public test cases if I remember. That's how you can check if your implementation of servers can update correctly the available time and queue status. You can also try to create coincidential input such that a customer is done serving while another one arrives, or more subtly a waiting customer is served while another one arrives. You might need to carefully think about this if you are rewriting the availiable time of servers

**Comment by nearsea00** [comment]
Sorry for the late reply, I still haven't managed to find the error in my code. I don't think the issue is what @somethingfishyfishy suggested. I did have that problem earlier but I think I fixed it already by updating the logic in my Wait event. I was also running into the problem @Yihan2407 pointed out but it was resolved by the change I made to rectify the previous problem.

Clearly, the implementation still isn't perfect though so like what @JerryWang0000 and @yiiilonggg suggested in this thread, I'll try creating more test cases and debugging statements to try to pinpoint the issue. I'll update the thread when I finally fix it, thanks for the help everyone!

**Comment by nearsea00** [comment]
Disregard my previous post, the problem with my code was exactly what @somethingfishyfishy suggested. My "solution" only accounted for cases where there's only 1 person in line, it didn't work for customers that joined as the 2nd in line and further. I was able to see this by creating a test file with 10 customers and 1 server with a qmax of 10 and setting the probrest to 1.0. Again, thanks for the help everyone.
