### ISSUE TITLE
? super T or ? extends T

### ISSUE THREAD

**Issue by vvivianfang** [nus-cs2030/2324-s1#73]
I am still confused when is it super or extends. In exercise 4, we use
ifPresentOrElse(Consumer<? super T> action, Runnable runnable) while orElseGet(Supplier<? extends T> supplier) according to the notes. but how can I tell when it is extends or super?

**Comment by Clementpng** [comment]
If we have an instance of type T, we can read it and use its attributes/methods as well as that of its parent classes, so we can use a Consumer of T or its parent classes (<? super T>). In contrast, we can't read a T and use the attributes/methods of its children classes.

For Supplier, we have to minimally produce a T, i.e produce a T or an instance of its child class (an extension of T). Since we minimally need to return a T, however, we can't produce a parent of T.

**Comment by nearsea00** [comment]
Remember PECS - Producer Extends, Consumer Super. If your method is taking in a parameter as input, it should be super; if it's returning a value, it should be extends

**Comment by ChoonHean** [comment]
Do take a look at recitation 4. Bounded wildcards were covered in there

**Comment by germaineee** [comment]
use PECS, for consumer you use ? super and since orElseGet takes in a supplier, it is a producer and you use ? extends. For Consumer, if you can accept say a float, it should also be able to accept a more general superclass, eg. number. For supplier,  if you have a method that takes in a supplier, say a Supplier<Shape>, it should be able to take in any of the subclasses, eg. Supplier<Circle>.
